name: Prebuild with Git Graph Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install VS Code
        run: |
          sudo apt update
          sudo apt install -y code

      - name: Install Git Graph Extension
        run: |
          code --install-extension mhutchie.git-graph

      - name: Verify Installed Extensions
        run: code --list-extensions
